[package]
name = "music-nft"
version = "1.1.0"
authors = ["rhythm4nft.near"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"
serde_json = "1.0.66"
